function buildComponentTokenMap(items: any): any {
  const map: any = {}

  function traverse(list: any) {
    for (const item of list) {
      const { mapTokens = [], multipleMapTokens = [], aliasTokens = [] } = item
      // mapTokens
      if (mapTokens.length) {
        for (const token of item.mapTokens) {
          if (token.components?.length) {
            for (const comp of token.components) {
              map[comp] = map[comp] || []
              map[comp].push(token.key)
            }
          }
        }
      }

      if (aliasTokens.length) {
        for (const token of item.aliasTokens) {
          if (token.components?.length) {
            for (const comp of token.components) {
              map[comp] = map[comp] || []
              map[comp].push(token.key)
            }
          }
        }
      }

      // multipleMapTokens
      if (multipleMapTokens.length) {
        for (const group of item.multipleMapTokens) {
          if (group.mapTokens?.length) {
            for (const token of group.mapTokens) {
              if (token.components?.length) {
                for (const comp of token.components) {
                  map[comp] = map[comp] || []
                  map[comp].push(token.key)
                }
              }
            }
          }
          if (group.aliasTokens?.length) {
            for (const token of group.aliasTokens) {
              if (token.components?.length) {
                for (const comp of token.components) {
                  map[comp] = map[comp] || []
                  map[comp].push(token.key)
                }
              }
            }
          }
        }
      }

      // children 递归
      if (item.children) traverse(item.children)
    }
  }

  traverse(items)
  return map
}

const colorMultipleMapTokens = [
  {
    title: '文本',
    key: 'text',
    mapTokens: [
      {
        key: 'colorText',
        title: '一级文本色',
        description: '最深的文本色。为了符合W3C标准，默认的文本颜色使用了该色，同时这个颜色也是最深的中性色',
        components: [
          'Alert',
          'Anchor',
          'App',
          'Avatar',
          'Badge',
          'Breadcrumb',
          'Button',
          'Calendar',
          'Card',
          'Carousel',
          'Cascader',
          'Checkbox',
          'Collapse',
          'DatePicker',
          'Descriptions',
          'Divider',
          'Drawer',
          'Dropdown',
          'FloatButton',
          'Form',
          'Image',
          'InputNumber',
          'Input',
          'Layout',
          'List',
          'Mentions',
          'Menu',
          'Message',
          'Modal',
          'Notification',
          'PageHeader',
          'Pagination',
          'Popconfirm',
          'Popover',
          'Progress',
          'QRCode',
          'Radio',
          'Rate',
          'Segmented',
          'Select',
          'Slider',
          'Spin',
          'Statistic',
          'Steps',
          'Switch',
          'Table',
          'Tabs',
          'Tag',
          'Timeline',
          'Tooltip',
          'Tour',
          'Transfer',
          'TreeSelect',
          'Tree',
          'Typography',
          'Upload',
        ],
      },
      {
        key: 'colorTextSecondary',
        title: '二级文本色',
        description:
          '作为第二梯度的文本色，一般用在不那么需要强化文本颜色的场景，例如 Label 文本、Menu 的文本选中态等场景。',
        components: ['Comment', 'Segmented', 'Steps'],
      },
      {
        key: 'colorTextTertiary',
        title: '三级文本色',
        description: '第三级文本色一般用于描述性文本，例如表单的中的补充说明文本、列表的描述性文本等场景。',
        components: [
          'Comment',
          'Input',
          'Select',
          'Switch',
          'Breadcrumb',
          'Card',
          'Cascader',
          'DatePicker',
          'Dropdown',
          'Form',
          'InputNumber',
          'List',
          'Menu',
          'Modal',
          'PageHeader',
          'Result',
          'Slider',
          'Spin',
          'Statistic',
          'Steps',
          'Table',
          'Tabs',
          'Tag',
          'Typography',
          'Upload',
          'Alert',
          'Calendar',
          'Drawer',
          'Notification',
          'Tour',
        ],
      },
      {
        key: 'colorTextQuaternary',
        title: '四级文本色',
        description: '第四级文本色是最浅的文本色，例如表单的输入提示文本、禁用色文本等。\n',
        components: [
          'Input',
          'Select',
          'Steps',
          'Switch',
          'Button',
          'Calendar',
          'Cascader',
          'Checkbox',
          'Collapse',
          'DatePicker',
          'Dropdown',
          'Empty',
          'InputNumber',
          'List',
          'Mentions',
          'Menu',
          'Pagination',
          'Radio',
          'Segmented',
          'Slider',
          'Table',
          'Tabs',
          'Timeline',
          'Transfer',
          'TreeSelect',
          'Tree',
          'Typography',
          'Upload',
          'Avatar',
          'Badge',
          'Comment',
        ],
      },
    ],
  },
  {
    title: '描边',
    key: 'outline',
    mapTokens: [
      {
        key: 'colorBorder',
        title: '一级边框色',
        description: '默认使用的边框颜色, 用于分割不同的元素，例如：表单的分割线、卡片的分割线等。',
        components: [
          'Button',
          'Cascader',
          'Checkbox',
          'Collapse',
          'DatePicker',
          'Form',
          'InputNumber',
          'Input',
          'List',
          'Mentions',
          'Pagination',
          'Radio',
          'Select',
          'Tabs',
          'Tag',
          'Transfer',
          'TreeSelect',
          'Tree',
          'Upload',
        ],
      },
      {
        key: 'colorBorderSecondary',
        title: '二级边框色',
        description: '比默认使用的边框色要浅一级，此颜色和 colorSplit 的颜色一致。使用的是实色。\n',
        components: [
          'Card',
          'Slider',
          'Steps',
          'Table',
          'Anchor',
          'Calendar',
          'Cascader',
          'DatePicker',
          'Descriptions',
          'Divider',
          'Drawer',
          'Dropdown',
          'FloatButton',
          'List',
          'Menu',
          'Modal',
          'Popover',
          'QRCode',
          'Select',
          'Tabs',
          'Timeline',
          'Transfer',
        ],
      },
    ],
  },
  {
    title: '填充',
    key: 'fill',
    mapTokens: [
      {
        key: 'colorFill',
        title: '一级填充色',
        description: '最深的填充色，用于拉开与二、三级填充色的区分度，目前只用在 Slider 的 hover 效果。',
        components: ['Skeleton', 'Tour', 'Slider', 'Button', 'Pagination', 'Radio'],
      },
      {
        key: 'colorFillSecondary',
        title: '二级填充色',
        description:
          '二级填充色可以较为明显地勾勒出元素形体，如 Rate、Skeleton 等。也可以作为三级填充色的 Hover 状态，如 Table 等。',
        components: [
          'Progress',
          'Segmented',
          'Select',
          'Slider',
          'Table',
          'Tag',
          'FloatButton',
          'Menu',
          'Rate',
          'Skeleton',
          'Steps',
          'Breadcrumb',
          'Button',
          'Pagination',
          'Tour',
        ],
      },
      {
        key: 'colorFillTertiary',
        title: '三级填充色',
        description:
          '三级填充色用于勾勒出元素形体的场景，如 Slider、Segmented 等。如无强调需求的情况下，建议使用三级填色作为默认填色。',
        components: [
          'Slider',
          'Tag',
          'Calendar',
          'Cascader',
          'DatePicker',
          'Dropdown',
          'FloatButton',
          'Mentions',
          'Select',
          'Steps',
          'Table',
          'Tabs',
          'Transfer',
          'TreeSelect',
          'Tree',
          'Upload',
          'Button',
          'Checkbox',
          'Image',
          'InputNumber',
          'Input',
          'Pagination',
          'Radio',
        ],
      },
      {
        key: 'colorFillQuaternary',
        title: '四级填充色',
        description: '最弱一级的填充色，适用于不易引起注意的色块，例如斑马纹、区分边界的色块等。',
        components: [
          'Button',
          'Card',
          'Collapse',
          'Descriptions',
          'InputNumber',
          'Input',
          'Menu',
          'Result',
          'Table',
          'Tabs',
          'Tag',
          'Upload',
        ],
      },
    ],
  },
  {
    title: '背景',
    key: 'background',
    mapTokens: [
      {
        key: 'colorBgContainer',
        title: '组件容器背景色',
        description: '组件的容器背景色，例如：默认按钮、输入框等。务必不要将其与 `colorBgElevated` 混淆。',
        components: [
          'Badge',
          'Button',
          'Calendar',
          'Card',
          'Carousel',
          'Cascader',
          'Checkbox',
          'Collapse',
          'DatePicker',
          'InputNumber',
          'Input',
          'Layout',
          'Mentions',
          'Menu',
          'PageHeader',
          'Pagination',
          'Progress',
          'Radio',
          'Select',
          'Slider',
          'Spin',
          'Steps',
          'Switch',
          'Table',
          'Tabs',
          'Timeline',
          'Tour',
          'Transfer',
          'TreeSelect',
          'Tree',
          'Avatar',
          'Anchor',
          'Descriptions',
          'Divider',
          'Drawer',
          'Dropdown',
          'FloatButton',
          'List',
          'Modal',
          'Popover',
          'QRCode',
          'Form',
        ],
      },
      {
        key: 'colorBgElevated',
        title: '浮层容器背景色',
        description:
          '浮层容器背景色，在暗色模式下该 token 的色值会比 `colorBgContainer` 要亮一些。例如：模态框、弹出框、菜单等。',
        components: [
          'DatePicker',
          'Drawer',
          'Dropdown',
          'FloatButton',
          'Mentions',
          'Menu',
          'Message',
          'Modal',
          'Notification',
          'Popover',
          'Segmented',
          'Select',
          'Slider',
          'TreeSelect',
        ],
      },
      {
        key: 'colorBgLayout',
        title: '布局背景色',
        description:
          '该色用于页面整体布局的背景色，只有需要在页面中处于 B1 的视觉层级时才会使用该 token，其他用法都是错误的',
        components: ['Layout', 'Segmented'],
      },
      {
        key: 'colorBgSpotlight',
        title: '引起注意的背景色',
        description: '该色用于引起用户强烈关注注意的背景色，目前只用在 Tooltip 的背景色上。',
        components: ['Tooltip'],
      },
      {
        key: 'colorBgMask',
        title: '浮层的背景蒙层颜色',
        description: '浮层的背景蒙层颜色，用于遮罩浮层下面的内容，Modal、Drawer 等组件的蒙层使用的是该 token',
        components: ['Drawer', 'Image', 'Modal', 'Upload'],
      },
    ],
  },
]

const seedTokenMap = [
  {
    key: 'color',
    title: '颜色',
    children: [
      {
        key: 'colorPrimary',
        title: '品牌色',
        description:
          '品牌色是体现产品特性和传播理念最直观的视觉元素之一。在你完成品牌主色的选取之后，我们会自动帮你生成一套完整的色板，并赋予它们有效的设计语义。',
        seedTokens: [
          {
            key: 'colorPrimary',
            title: '品牌主色',
            description:
              '品牌色是体现产品特性和传播理念最直观的视觉元素之一。在你完成品牌主色的选取之后，我们会自动帮你生成一套完整的色板，并赋予它们有效的设计语义。',
          },
        ],
        mapTokens: [
          {
            key: 'colorPrimaryBg',
            title: '主色浅色背景色',
            description: '主色浅色背景颜色，一般用于视觉层级较弱的选中状态。',
            components: [
              'Calendar',
              'Cascader',
              'DatePicker',
              'Dropdown',
              'Menu',
              'Select',
              'Steps',
              'Table',
              'Transfer',
              'TreeSelect',
              'Tree',
              'Button',
              'Form',
              'InputNumber',
              'Input',
              'Mentions',
              'Pagination',
              'Radio',
            ],
          },
          {
            key: 'colorPrimaryBgHover',
            title: '主色浅色背景悬浮态',
            description: '与主色浅色背景颜色相对应的悬浮态颜色。',
            components: ['Dropdown', 'Table', 'Transfer'],
          },
          {
            key: 'colorPrimaryBorder',
            title: '主色描边色',
            description: '主色梯度下的描边用色，用在 Slider 组件的描边上',
            components: [
              'Breadcrumb',
              'Button',
              'Cascader',
              'Checkbox',
              'DatePicker',
              'Dropdown',
              'Menu',
              'Modal',
              'Pagination',
              'Radio',
              'Slider',
              'Switch',
              'Tabs',
              'TreeSelect',
              'Tree',
            ],
          },
          {
            key: 'colorPrimaryBorderHover',
            title: '主色描边色悬浮态',
            description: '主色梯度下的描边用色的悬浮态，Slider 、Button 等组件的描边 Hover 时会使用',
            components: ['Slider'],
          },
          {
            key: 'colorPrimaryHover',
            title: '主色悬浮态',
            description: '主色梯度下的悬浮态，使用频率很高',
            components: [
              'Button',
              'Calendar',
              'Cascader',
              'Checkbox',
              'DatePicker',
              'FloatButton',
              'InputNumber',
              'Input',
              'Mentions',
              'Pagination',
              'Radio',
              'Select',
              'Switch',
              'Tabs',
              'Tag',
              'TreeSelect',
              'Tree',
              'Typography',
              'Upload',
            ],
          },
          {
            key: 'colorPrimary',
            title: '品牌主色',
            description:
              '品牌色是体现产品特性和传播理念最直观的视觉元素之一。在你完成品牌主色的选取之后，我们会自动帮你生成一套完整的色板，并赋予它们有效的设计语义',
            components: [
              'Anchor',
              'Badge',
              'Button',
              'Calendar',
              'Card',
              'Cascader',
              'Checkbox',
              'DatePicker',
              'Dropdown',
              'FloatButton',
              'Form',
              'InputNumber',
              'Input',
              'List',
              'Menu',
              'Pagination',
              'Radio',
              'Select',
              'Slider',
              'Spin',
              'Steps',
              'Switch',
              'Table',
              'Tabs',
              'Tag',
              'Timeline',
              'Tour',
              'TreeSelect',
              'Tree',
              'Upload',
            ],
          },
          {
            key: 'colorPrimaryActive',
            title: '主色激活态',
            description: '主色梯度下的深色激活态',
            components: ['Button', 'Input', 'Radio', 'Tabs', 'Tag'],
          },
          {
            key: 'colorPrimaryTextHover',
            title: '主色文本悬浮态',
            description: '主色梯度下的文本悬浮态',
            components: [],
          },
          {
            key: 'colorPrimaryText',
            title: '主色文本',
            description: '主色梯度下的文本颜色',
            components: [],
          },
          {
            key: 'colorPrimaryTextActive',
            title: '主色文本激活',
            description: '主色梯度下的文本激活态',
            components: [],
          },
        ],
        aliasTokens: [
          {
            key: 'controlItemBgActive',
            title: '',
            description: '',
            components: [
              'Calendar',
              'Cascader',
              'DatePicker',
              'Dropdown',
              'Menu',
              'Select',
              'Steps',
              'Table',
              'Transfer',
              'TreeSelect',
              'Tree',
            ],
          },
          {
            key: 'controlItemBgActiveHover',
            title: '',
            description: '',
            components: ['Dropdown', 'Table', 'Transfer'],
          },
          {
            key: 'controlOutline',
            title: '',
            description: '',
            components: [
              'Button',
              'DatePicker',
              'Form',
              'InputNumber',
              'Input',
              'Mentions',
              'Pagination',
              'Radio',
              'Select',
            ],
          },
        ],
      },
      {
        key: 'colorSuccess',
        title: '成功色',
        seedTokens: [
          {
            key: 'colorSuccess',
            title: '成功色',
            description: '用于表示操作成功的 Token 序列，如 Result、Progress 等组件会使用该组梯度变量。',
          },
        ],
        mapTokens: [
          {
            key: 'colorSuccessBg',
            title: '成功色的浅色背景颜色',
            description: '成功色的浅色背景颜色，用于 Tag 和 Alert 的成功态背景色',
            components: ['Alert', 'Tag'],
          },
          {
            key: 'colorSuccessBgHover',
            title: '成功色的浅色背景色悬浮态',
            description: '成功色浅色背景颜色，一般用于视觉层级较弱的选中状态，不过 antd 目前没有使用到该 token',
            components: [],
          },
          {
            key: 'colorSuccessBorder',
            title: '成功色的描边色',
            description: '成功色的描边色，用于 Tag 和 Alert 的成功态描边色',
            components: ['Alert', 'Tag'],
          },
          {
            key: 'colorSuccessBorderHover',
            title: '成功色的描边色悬浮态',
            description: '成功色的描边色悬浮态',
            components: [],
          },
          {
            key: 'colorSuccessHover',
            title: '成功色的深色悬浮态',
            description: '成功色的深色悬浮态',
            components: [],
          },
          {
            key: 'colorSuccessActive',
            title: '成功色的深色激活态',
            description: '成功色的深色激活态',
            components: [],
          },
          {
            key: 'colorSuccess',
            title: '成功色',
            description: '用于表示操作成功的 Token 序列，如 Result、Progress 等组件会使用该组梯度变量。',
            components: [
              'Alert',
              'Badge',
              'Form',
              'Input',
              'Message',
              'Modal',
              'Notification',
              'Progress',
              'Result',
              'Tag',
              'Timeline',
              'Typography',
            ],
          },
          {
            key: 'colorSuccessTextHover',
            title: '成功色的文本悬浮态',
            description: '成功色的文本悬浮态',
            components: [],
          },
          {
            key: 'colorSuccessText',
            title: '成功色的文本默认态',
            description: '成功色的文本默认态',
            components: [],
          },
          {
            key: 'colorSuccessTextActive',
            title: '成功色的文本激活态',
            description: '成功色的文本激活态',
            components: [],
          },
        ],
      },
      {
        key: 'colorWarning',
        title: '警戒色',
        seedTokens: [
          {
            key: 'colorWarning',
            title: '警戒色',
            description:
              '用于表示操作警告的 Token 序列，如 Notification、 Alert等警告类组件或 Input 输入类等组件会使用该组梯度变量。',
          },
        ],
        mapTokens: [
          {
            key: 'colorWarningBg',
            title: '警戒色的浅色背景颜色',
            description: '',
            components: ['Alert', 'Tag', 'DatePicker', 'InputNumber', 'Input', 'Mentions', 'Select'],
          },
          {
            key: 'colorWarningBorder',
            title: '警戒色的描边色',
            description: '警戒色的描边色',
            components: ['Alert', 'Tag'],
          },
          {
            key: 'colorWarningBorderHover',
            title: '警戒色的描边色悬浮态',
            description: '警戒色的描边色悬浮态',
            components: ['InputNumber', 'Input', 'Mentions'],
          },
          {
            key: 'colorWarningHover',
            title: '警戒色的深色悬浮态',
            description: '警戒色的深色悬浮态',
            components: ['Select'],
          },
          {
            key: 'colorWarning',
            title: '警戒色',
            description:
              '用于表示操作警告的 Token 序列，如 Notification、 Alert等警告类组件或 Input 输入类等组件会使用该组梯度变量。',
            components: [
              'Alert',
              'Badge',
              'DatePicker',
              'Form',
              'InputNumber',
              'Input',
              'Mentions',
              'Message',
              'Modal',
              'Notification',
              'Popconfirm',
              'Result',
              'Tag',
              'Transfer',
              'Typography',
            ],
          },
          {
            key: 'colorWarningActive',
            title: '警戒色的深色激活态',
            description: '警戒色的深色激活态',
            components: [],
          },
          {
            key: 'colorWarningTextHover',
            title: '警戒色的文本悬浮态',
            description: '警戒色的文本悬浮态',
            components: [],
          },
          {
            key: 'colorWarningText',
            title: '警戒色的文本默认态',
            description: '警戒色的文本默认态',
            components: [],
          },
          {
            key: 'colorWarningTextActive',
            title: '警戒色的文本激活态',
            description: '警戒色的文本激活态',
            components: [],
          },
        ],
        aliasTokens: [
          {
            key: 'colorWarningOutline',
            title: '',
            description: '',
            components: ['DatePicker', 'InputNumber', 'Input', 'Mentions', 'Select'],
          },
        ],
      },
      {
        key: 'colorError',
        title: '错误色',
        seedTokens: [
          {
            key: 'colorError',
            title: '错误色',
            description: '用于表示操作失败的 Token 序列，如失败按钮、错误状态提示（Result）组件等。',
          },
        ],
        mapTokens: [
          {
            key: 'colorErrorBg',
            title: '错误色的浅色背景颜色',
            description: '',
            components: [
              'Alert',
              'Button',
              'Menu',
              'Tag',
              'Upload',
              'DatePicker',
              'InputNumber',
              'Input',
              'Mentions',
              'Select',
            ],
          },
          {
            key: 'colorErrorBgHover',
            title: '错误色的浅色背景色悬浮态',
            description: '',
            components: [],
          },
          {
            key: 'colorErrorBorder',
            title: '错误色的描边色',
            description: '',
            components: ['Alert', 'Tag'],
          },
          {
            key: 'colorErrorBorderHover',
            title: '错误色的描边色悬浮态',
            description: '',
            components: ['Button', 'InputNumber', 'Input', 'Mentions'],
          },
          {
            key: 'colorErrorHover',
            title: '错误色的深色悬浮态',
            description: '',
            components: ['Badge', 'Button', 'Menu', 'Select', 'Typography'],
          },
          {
            key: 'colorError',
            title: '错误色',
            description: '用于表示操作失败的 Token 序列，如失败按钮、错误状态提示（Result）组件等。',
            components: [
              'Alert',
              'Badge',
              'Button',
              'DatePicker',
              'Dropdown',
              'Form',
              'InputNumber',
              'Input',
              'Mentions',
              'Menu',
              'Message',
              'Modal',
              'Notification',
              'Progress',
              'Result',
              'Steps',
              'Tag',
              'Timeline',
              'Transfer',
              'Typography',
              'Upload',
            ],
          },
          {
            key: 'colorErrorActive',
            title: '错误色的深色激活态',
            description: '',
            components: ['Button', 'Typography'],
          },
          {
            key: 'colorErrorTextHover',
            title: '错误色的文本悬浮态',
            description: '',
            components: [],
          },
          {
            key: 'colorErrorText',
            title: '错误色的文本默认态',
            description: '',
            components: [],
          },
          {
            key: 'colorErrorTextActive',
            title: '错误色的文本激活态',
            description: '',
            components: [],
          },
        ],
        aliasTokens: [
          {
            key: 'colorErrorOutline',
            title: '',
            description: '',
            components: ['Button', 'DatePicker', 'InputNumber', 'Input', 'Mentions', 'Select'],
          },
          {
            key: 'colorHighlight',
            title: '',
            description: '',
            components: ['Cascader'],
          },
        ],
      },
      {
        key: 'colorInfo',
        title: '信息色',
        seedTokens: [
          {
            key: 'colorInfo',
            title: '信息色',
            description: '用于表示操作信息的 Token 序列，如 Alert 、Tag、 Progress 等组件都有用到该组梯度变量。',
          },
        ],
        mapTokens: [
          {
            key: 'colorInfoBg',
            title: '信息色的浅色背景颜色',
            description: '信息色的浅色背景颜色',
            components: ['Alert', 'Tag'],
          },
          {
            key: 'colorInfoBgHover',
            title: '信息色的浅色背景色悬浮态',
            description: '信息色的浅色背景色悬浮态',
            components: [],
          },
          {
            key: 'colorInfoBorder',
            title: '信息色的描边色',
            description: '',
            components: ['Alert', 'Tag'],
          },
          {
            key: 'colorInfoBorderHover',
            title: '信息色的描边色悬浮态',
            description: '',
            components: [],
          },
          {
            key: 'colorInfoHover',
            title: '信息色的深色悬浮态',
            description: '',
            components: ['Button', 'Calendar', 'DatePicker', 'PageHeader', 'Table', 'Transfer', 'Typography'],
          },
          {
            key: 'colorInfo',
            title: '信息色',
            description: '用于表示操作信息的 Token 序列，如 Alert 、Tag、 Progress 等组件都有用到该组梯度变量。',
            components: ['Alert', 'Message', 'Modal', 'Notification', 'Progress', 'Result', 'Tag'],
          },
          {
            key: 'colorInfoActive',
            title: '信息色的深色激活态',
            description: '',
            components: ['Button', 'Calendar', 'DatePicker', 'PageHeader', 'Table', 'Typography'],
          },
          {
            key: 'colorInfoTextHover',
            title: '信息色的文本悬浮态',
            description: '',
            components: [],
          },
          {
            key: 'colorInfoText',
            title: '信息色的文本默认态',
            description: '',
            components: ['Button', 'Calendar', 'DatePicker', 'PageHeader', 'Table', 'Typography'],
          },
          {
            key: 'colorInfoTextActive',
            title: '信息色的文本激活态',
            description: '',
            components: [],
          },
        ],
        aliasTokens: [
          {
            key: 'colorLink',
            title: '',
            description: '',
            components: ['Button', 'Calendar', 'DatePicker', 'PageHeader', 'Table', 'Typography'],
          },
          {
            key: 'colorLinkActive',
            title: '',
            description: '',
            components: ['Button', 'Calendar', 'DatePicker', 'PageHeader', 'Table', 'Typography'],
          },
          {
            key: 'colorLinkHover',
            title: '',
            description: '',
            components: ['Button', 'Calendar', 'DatePicker', 'PageHeader', 'Table', 'Transfer', 'Typography'],
          },
        ],
      },
      {
        key: 'NeutralColor',
        title: '中性色',
        description:
          '中性色主要被大量的应用在界面的文字、背景、边框和填充的 4 种场景。合理地选择中性色能够令页面信息具备良好的主次关系，助力阅读体验。',
        seedTokens: [
          {
            key: 'colorTextBase',
            title: '基础文本色',
            description:
              '用于派生文本色梯度的基础变量，v5 中我们添加了一层文本色的派生算法可以产出梯度明确的文本色的梯度变量。但**请不要在代码中直接使用该 Seed Token**！',
          },
          {
            key: 'colorBgBase',
            title: '基础背景色',
            description:
              '用于派生背景色梯度的基础变量，v5 中我们添加了一层背景色的派生算法可以产出梯度明确的背景色的梯度变量。但 **请不要在代码中直接使用该 Seed Token** ！',
          },
        ],
        multipleMapTokens: colorMultipleMapTokens,
        flatMapTokens: colorMultipleMapTokens.flatMap((item) => item.mapTokens),
        aliasTokens: [
          {
            key: 'colorBorderBg',
            title: '',
            description: '',
            components: ['Avatar', 'Badge', 'Steps'],
          },
          {
            key: 'controlTmpOutline',
            title: '',
            description: '',
            components: ['Button'],
          },
          {
            key: 'colorFillAlter',
            title: '',
            description: '',
            components: [
              'Card',
              'Collapse',
              'Descriptions',
              'InputNumber',
              'Input',
              'Menu',
              'Result',
              'Table',
              'Tabs',
              'Tag',
              'Upload',
            ],
          },
          {
            key: 'colorFillContent',
            title: '',
            description: '',
            components: ['FloatButton', 'Menu', 'Rate', 'Skeleton', 'Steps', 'Table'],
          },
          {
            key: 'colorFillContentHover',
            title: '',
            description: '',
            components: ['Slider'],
          },
          {
            key: 'controlItemBgHover',
            title: '',
            description: '',
            components: [
              'Calendar',
              'Cascader',
              'DatePicker',
              'Dropdown',
              'FloatButton',
              'Mentions',
              'Select',
              'Steps',
              'Table',
              'Tabs',
              'Transfer',
              'TreeSelect',
              'Tree',
              'Upload',
            ],
          },
          {
            key: 'colorBgContainerDisabled',
            title: '',
            description: '',
            components: [
              'Button',
              'Calendar',
              'Cascader',
              'Checkbox',
              'DatePicker',
              'Image',
              'InputNumber',
              'Input',
              'Mentions',
              'Pagination',
              'Radio',
              'Select',
              'Transfer',
              'TreeSelect',
              'Tree',
            ],
          },
          {
            key: 'colorBgTextActive',
            title: '',
            description: '',
            components: ['Button', 'Pagination'],
          },
          {
            key: 'colorBgTextHover',
            title: '',
            description: '',
            components: ['Breadcrumb', 'Button', 'Menu', 'Pagination', 'Tour'],
          },
          {
            key: 'colorErrorOutline',
            title: '',
            description: '',
            components: ['Button', 'DatePicker', 'InputNumber', 'Input', 'Mentions', 'Select'],
          },
          {
            key: 'colorSplit',
            title: '',
            description: '用于作为分割线的颜色，此颜色和 colorBorderSecondary 的颜色一致，但是用的是透明色。',
            components: [
              'Anchor',
              'Calendar',
              'Cascader',
              'DatePicker',
              'Descriptions',
              'Divider',
              'Drawer',
              'Dropdown',
              'FloatButton',
              'List',
              'Menu',
              'Modal',
              'Popover',
              'QRCode',
              'Select',
              'Steps',
              'Table',
              'Tabs',
              'Timeline',
              'Transfer',
            ],
          },
          {
            key: 'colorWarningOutline',
            title: '',
            description: '',
            components: ['DatePicker', 'InputNumber', 'Input', 'Mentions', 'Select'],
          },
          {
            key: 'controlItemBgActiveDisabled',
            title: '',
            description: '',
            components: ['Pagination', 'Radio'],
          },
          {
            key: 'controlOutline',
            title: '',
            description: '',
            components: [
              'Button',
              'DatePicker',
              'Form',
              'InputNumber',
              'Input',
              'Mentions',
              'Pagination',
              'Radio',
              'Select',
            ],
          },
        ],
      },
    ],
  },
  {
    key: 'size',
    title: '尺寸',
    children: [
      {
        key: 'MultipleText',
        title: '文字',
        seedTokens: [
          {
            key: 'fontSize',
            title: '默认字号',
            description: '设计系统中使用最广泛的字体大小，文本梯度也将基于该字号进行派生。',
          },
        ],
        multipleMapTokens: [
          {
            title: '字号',
            key: 'fontSize',
            mapTokens: [
              {
                key: 'fontSize',
                title: '默认字号',
                description: '设计系统中使用最广泛的字体大小，文本梯度也将基于该字号进行派生。',
                components: [
                  'Alert',
                  'Anchor',
                  'App',
                  'Avatar',
                  'Badge',
                  'Breadcrumb',
                  'Button',
                  'Calendar',
                  'Card',
                  'Carousel',
                  'Cascader',
                  'Checkbox',
                  'Collapse',
                  'Comment',
                  'DatePicker',
                  'Descriptions',
                  'Divider',
                  'Dropdown',
                  'Empty',
                  'FloatButton',
                  'Form',
                  'Image',
                  'InputNumber',
                  'Input',
                  'Layout',
                  'List',
                  'Mentions',
                  'Menu',
                  'Message',
                  'Modal',
                  'Notification',
                  'PageHeader',
                  'Pagination',
                  'Popconfirm',
                  'Popover',
                  'Progress',
                  'QRCode',
                  'Radio',
                  'Rate',
                  'Result',
                  'Segmented',
                  'Select',
                  'Slider',
                  'Spin',
                  'Statistic',
                  'Steps',
                  'Switch',
                  'Table',
                  'Tabs',
                  'Tag',
                  'Timeline',
                  'Tooltip',
                  'Tour',
                  'Transfer',
                  'TreeSelect',
                  'Tree',
                  'Typography',
                  'Upload',
                ],
              },
              {
                key: 'fontSizeSM',
                title: '',
                description: '',
                components: [
                  'Badge',
                  'Calendar',
                  'Comment',
                  'Descriptions',
                  'Dropdown',
                  'FloatButton',
                  'InputNumber',
                  'Input',
                  'List',
                  'Menu',
                  'Pagination',
                  'Progress',
                  'Select',
                  'Steps',
                  'Switch',
                  'Table',
                  'Tabs',
                  'Tag',
                  'Timeline',
                ],
              },
              {
                key: 'fontSizeLG',
                title: '',
                description: '',
                components: [
                  'Alert',
                  'Anchor',
                  'Avatar',
                  'Button',
                  'Calendar',
                  'Card',
                  'Cascader',
                  'Checkbox',
                  'DatePicker',
                  'Descriptions',
                  'Divider',
                  'Drawer',
                  'FloatButton',
                  'Form',
                  'InputNumber',
                  'Input',
                  'List',
                  'Mentions',
                  'Menu',
                  'Message',
                  'Modal',
                  'Notification',
                  'PageHeader',
                  'Pagination',
                  'Radio',
                  'Segmented',
                  'Select',
                  'Steps',
                  'Tabs',
                  'TreeSelect',
                  'Tree',
                  'Typography',
                  'Upload',
                ],
              },
              {
                key: 'fontSizeXL',
                title: '',
                description: '',
                components: ['Avatar', 'Layout'],
              },
              {
                key: 'fontSizeHeading1',
                title: '一级标题字号',
                description: 'H1 标签所使用的字号',
                components: ['Typography'],
              },
              {
                key: 'fontSizeHeading2',
                title: '二级标题字号',
                description: 'h2 标签所使用的字号',
                components: ['Typography', 'Upload'],
              },
              {
                key: 'fontSizeHeading3',
                title: '三级标题字号',
                description: 'h3 标签所使用的字号',
                components: ['Alert', 'Avatar', 'Result', 'Statistic', 'Steps', 'Typography', 'Upload'],
              },
              {
                key: 'fontSizeHeading4',
                title: '四级标题字号',
                description: 'h4 标签所使用的字号',
                components: ['PageHeader', 'Typography'],
              },
              {
                key: 'fontSizeHeading5',
                title: '五级标题字号',
                description: 'h5 标签所使用的字号',
                components: ['Modal', 'Typography'],
              },
            ],
          },
          {
            title: '行高',
            key: 'lineHeight',
            mapTokens: [
              {
                key: 'lineHeight',
                title: '',
                description: '',
                components: [
                  'Alert',
                  'Anchor',
                  'App',
                  'Avatar',
                  'Badge',
                  'Breadcrumb',
                  'Button',
                  'Calendar',
                  'Card',
                  'Carousel',
                  'Cascader',
                  'Checkbox',
                  'Collapse',
                  'DatePicker',
                  'Descriptions',
                  'Divider',
                  'Dropdown',
                  'Empty',
                  'FloatButton',
                  'Form',
                  'Image',
                  'InputNumber',
                  'Input',
                  'List',
                  'Mentions',
                  'Menu',
                  'Message',
                  'Modal',
                  'Notification',
                  'PageHeader',
                  'Pagination',
                  'Popconfirm',
                  'Popover',
                  'Progress',
                  'QRCode',
                  'Radio',
                  'Rate',
                  'Result',
                  'Segmented',
                  'Select',
                  'Slider',
                  'Spin',
                  'Statistic',
                  'Steps',
                  'Switch',
                  'Table',
                  'Tabs',
                  'Tag',
                  'Timeline',
                  'Tooltip',
                  'Tour',
                  'Transfer',
                  'TreeSelect',
                  'Tree',
                  'Typography',
                  'Upload',
                ],
              },
              {
                key: 'lineHeightSM',
                title: '',
                description: '',
                components: ['Calendar', 'Descriptions', 'Steps'],
              },
              {
                key: 'lineHeightLG',
                title: '',
                description: '',
                components: [
                  'Calendar',
                  'Card',
                  'DatePicker',
                  'Descriptions',
                  'Drawer',
                  'InputNumber',
                  'Input',
                  'List',
                  'Mentions',
                  'Notification',
                  'Pagination',
                  'Typography',
                ],
              },
              {
                key: 'lineHeightHeading1',
                title: '',
                description: '',
                components: ['Typography'],
              },
              {
                key: 'lineHeightHeading2',
                title: '',
                description: '',
                components: ['Typography'],
              },
              {
                key: 'lineHeightHeading3',
                title: '',
                description: '',
                components: ['Result', 'Typography'],
              },
              {
                key: 'lineHeightHeading4',
                title: '',
                description: '',
                components: ['Typography'],
              },
              {
                key: 'lineHeightHeading5',
                title: '',
                description: '',
                components: ['Modal', 'Typography'],
              },
            ],
          },
        ],
      },
      {
        key: 'spacing',
        title: '间距',
        seedTokens: [
          {
            key: 'sizeStep',
            title: '尺寸步长',
            description:
              '用于控制组件尺寸的基础步长，尺寸步长结合尺寸变化单位，就可以派生各种尺寸梯度。通过调整步长即可得到不同的布局模式，例如 V5 紧凑模式下的尺寸步长为 2',
          },
          {
            key: 'sizeUnit',
            title: '尺寸变化单位',
            description: '用于控制组件尺寸的变化单位，在 Ant Design 中我们的基础单位为 4 ，便于更加细致地控制尺寸梯度',
          },
        ],
        multipleMapTokens: [
          {
            key: 'margin',
            title: '外间距',
            mapTokens: [
              {
                key: 'marginXXS',
                title: '',
                description: '',
                components: [
                  'Avatar',
                  'Breadcrumb',
                  'Calendar',
                  'Card',
                  'Carousel',
                  'Comment',
                  'DatePicker',
                  'Descriptions',
                  'Dropdown',
                  'Form',
                  'Image',
                  'Layout',
                  'List',
                  'Menu',
                  'Pagination',
                  'Popover',
                  'Progress',
                  'Skeleton',
                  'Spin',
                  'Statistic',
                  'Steps',
                  'Switch',
                  'Table',
                  'Tabs',
                  'Timeline',
                  'Tooltip',
                  'Tour',
                  'Transfer',
                  'Typography',
                  'Upload',
                ],
              },
              {
                key: 'marginXS',
                title: '',
                description: '',
                components: [
                  'Alert',
                  'Avatar',
                  'Badge',
                  'Breadcrumb',
                  'Button',
                  'Calendar',
                  'Card',
                  'Cascader',
                  'Checkbox',
                  'DatePicker',
                  'Descriptions',
                  'Divider',
                  'Dropdown',
                  'Empty',
                  'Form',
                  'Menu',
                  'Message',
                  'Modal',
                  'Notification',
                  'PageHeader',
                  'Pagination',
                  'Popconfirm',
                  'Popover',
                  'Progress',
                  'QRCode',
                  'Radio',
                  'Rate',
                  'Result',
                  'Steps',
                  'Tabs',
                  'Tag',
                  'Timeline',
                  'Tour',
                  'Transfer',
                  'TreeSelect',
                  'Tree',
                  'Typography',
                  'Upload',
                ],
              },
              {
                key: 'marginSM',
                title: '',
                description: '',
                components: [
                  'Alert',
                  'Collapse',
                  'Comment',
                  'Drawer',
                  'Image',
                  'List',
                  'Modal',
                  'Notification',
                  'PageHeader',
                  'Pagination',
                  'Segmented',
                  'Skeleton',
                  'Steps',
                  'Tabs',
                  'Timeline',
                ],
              },
              {
                key: 'margin',
                title: '',
                description: '',
                components: [
                  'Divider',
                  'Empty',
                  'FloatButton',
                  'Form',
                  'List',
                  'Menu',
                  'Modal',
                  'Notification',
                  'Pagination',
                  'Steps',
                  'Table',
                  'Tabs',
                  'Timeline',
                  'Transfer',
                  'Upload',
                ],
              },
              {
                key: 'marginMD',
                title: '',
                description: '',
                components: ['PageHeader'],
              },
              {
                key: 'marginLG',
                title: '',
                description: '',
                components: ['Divider', 'FloatButton', 'Form', 'List', 'Modal', 'Notification', 'Skeleton', 'Steps'],
              },
              {
                key: 'marginXL',
                title: '',
                description: '',
                components: ['Empty', 'Upload'],
              },
              {
                key: 'marginXXL',
                title: '',
                description: '',
                components: ['FloatButton', 'List'],
              },
            ],
          },
          {
            key: 'padding',
            title: '内间距',
            mapTokens: [
              {
                key: 'paddingXXS',
                title: '',
                description: '',
                components: [
                  'Anchor',
                  'Breadcrumb',
                  'Calendar',
                  'Cascader',
                  'Collapse',
                  'DatePicker',
                  'Dropdown',
                  'FloatButton',
                  'Image',
                  'InputNumber',
                  'Input',
                  'Mentions',
                  'Pagination',
                  'Segmented',
                  'Select',
                  'Steps',
                  'Table',
                  'Tabs',
                  'Tag',
                  'Timeline',
                  'Typography',
                ],
              },
              {
                key: 'paddingXS',
                title: '',
                description: '',
                components: [
                  'Badge',
                  'Button',
                  'Calendar',
                  'Card',
                  'Cascader',
                  'Checkbox',
                  'Comment',
                  'DatePicker',
                  'Descriptions',
                  'Drawer',
                  'Dropdown',
                  'Flex',
                  'Form',
                  'InputNumber',
                  'Input',
                  'List',
                  'Mentions',
                  'Menu',
                  'Message',
                  'Modal',
                  'PageHeader',
                  'Pagination',
                  'Progress',
                  'Radio',
                  'Result',
                  'Select',
                  'Steps',
                  'Table',
                  'Tabs',
                  'Tooltip',
                  'Tour',
                  'Transfer',
                  'TreeSelect',
                  'Tree',
                  'Typography',
                  'Upload',
                ],
              },
              {
                key: 'paddingSM',
                title: '',
                description: '',
                components: [
                  'Calendar',
                  'Card',
                  'Cascader',
                  'Collapse',
                  'DatePicker',
                  'Descriptions',
                  'Form',
                  'Image',
                  'InputNumber',
                  'Input',
                  'List',
                  'Mentions',
                  'Message',
                  'PageHeader',
                  'Pagination',
                  'Popover',
                  'QRCode',
                  'Select',
                  'Steps',
                  'Table',
                  'Tabs',
                  'Tooltip',
                  'Transfer',
                  'Typography',
                  'Upload',
                ],
              },
              {
                key: 'padding',
                title: '',
                description: '',
                components: [
                  'Anchor',
                  'Card',
                  'Collapse',
                  'Descriptions',
                  'Drawer',
                  'Flex',
                  'List',
                  'Menu',
                  'Modal',
                  'Popover',
                  'Radio',
                  'Result',
                  'Skeleton',
                  'Statistic',
                  'Steps',
                  'Table',
                  'Tabs',
                  'Timeline',
                  'Tour',
                  'Upload',
                ],
              },
              {
                key: 'paddingMD',
                title: '',
                description: '',
                components: ['Alert', 'Comment', 'Modal', 'Notification', 'PageHeader'],
              },
              {
                key: 'paddingLG',
                title: '',
                description: '',
                components: [
                  'Card',
                  'Descriptions',
                  'Drawer',
                  'Flex',
                  'Input',
                  'List',
                  'Modal',
                  'Notification',
                  'PageHeader',
                  'Result',
                  'Steps',
                  'Tabs',
                ],
              },
              {
                key: 'paddingXL',
                title: '',
                description: '',
                components: ['Menu', 'Result'],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    key: 'form',
    title: '风格',
    children: [
      {
        key: 'borderRadius',
        title: '圆角',
        seedTokens: [
          {
            key: 'borderRadius',
            title: '基础圆角',
            description: '基础组件的圆角大小，例如按钮、输入框、卡片等',
          },
        ],
        mapTokens: [
          {
            key: 'borderRadius',
            title: '基础圆角',
            description: '基础组件的圆角大小，例如按钮、输入框、卡片等',
            components: [
              'Avatar',
              'Button',
              'Calendar',
              'DatePicker',
              'InputNumber',
              'Input',
              'Layout',
              'Mentions',
              'Menu',
              'Pagination',
              'Radio',
              'Segmented',
              'Select',
              'Table',
              'Tabs',
              'Tooltip',
              'Tour',
              'TreeSelect',
              'Tree',
            ],
          },
          {
            key: 'borderRadiusSM',
            title: 'SM号圆角',
            description:
              'SM号圆角，用于组件小尺寸下的圆角，如 Button、Input、Select 等输入类控件在 small size 下的圆角',
            components: [
              'Avatar',
              'Badge',
              'Breadcrumb',
              'Button',
              'Calendar',
              'Cascader',
              'Checkbox',
              'DatePicker',
              'Dropdown',
              'FloatButton',
              'InputNumber',
              'Input',
              'Mentions',
              'Menu',
              'Modal',
              'Notification',
              'Pagination',
              'Radio',
              'Segmented',
              'Select',
              'Skeleton',
              'Steps',
              'Tag',
              'Tour',
              'TreeSelect',
              'Tree',
            ],
          },
          {
            key: 'borderRadiusLG',
            title: 'LG号圆角',
            description: 'LG号圆角，用于组件中的一些大圆角，如 Card、Modal 等一些组件样式。',
            components: [
              'Alert',
              'Avatar',
              'Button',
              'Calendar',
              'Card',
              'Collapse',
              'DatePicker',
              'Descriptions',
              'Dropdown',
              'FloatButton',
              'InputNumber',
              'Input',
              'List',
              'Mentions',
              'Menu',
              'Message',
              'Modal',
              'Notification',
              'Pagination',
              'Popover',
              'QRCode',
              'Radio',
              'Segmented',
              'Select',
              'Table',
              'Tabs',
              'Tour',
              'Transfer',
              'Upload',
            ],
          },
          {
            key: 'borderRadiusXS',
            title: 'XS号圆角',
            description: 'XS号圆角，用于组件中的一些小圆角，如 Segmented 、Arrow 等一些内部圆角的组件样式中。',
            components: ['DatePicker', 'Dropdown', 'Popover', 'Segmented', 'Select', 'Slider', 'Tooltip', 'Tour'],
          },
        ],
      },
      {
        key: 'boxShadow',
        title: '阴影',
        seedTokens: [],
        mapTokens: [
          {
            key: 'boxShadow',
            title: '',
            description: '',
            components: ['Card', 'Segmented'],
          },
          {
            key: 'boxShadowSecondary',
            title: '',
            description: '',
            components: [
              'DatePicker',
              'Dropdown',
              'FloatButton',
              'Mentions',
              'Menu',
              'Message',
              'Modal',
              'Notification',
              'Popover',
              'Select',
              'Table',
              'Tabs',
              'Tooltip',
            ],
          },
        ],
      },
    ],
  },
  {
    key: 'other',
    title: '其他',
    children: [
      {
        key: 'other',
        title: '其它',
        seedTokens: [
          {
            key: 'wireframe',
            title: '线框风格',
            description: '用于将组件的视觉效果变为线框化，如果需要使用 V4 的效果，需要开启配置项',
          },
        ],
      },
    ],
  },
]

export const componentTokenMap = buildComponentTokenMap(seedTokenMap)

export default seedTokenMap
